In [2]:
import numpy as np

def dfs(mat, start):
    n = len(mat)
    st = [] # LIFO queue
    visited = [False for _ in range(n)]

    st.append(start)

    while st:
        curr_v = st.pop()
        visited[curr_v] = True # visit new vertex
        for neigh in range(n):
            if neigh != curr_v and abs(mat[curr_v][neigh]) > 0: # check the neighbours of current vertex
                if visited[neigh] == False:
                    st.append(neigh)

    for i in range(n): # check if all vertecies were visited
        if visited[i] == False:
            return True

    return False

from queue import Queue

def bfs(mat, start):
    n = len(mat)
    queue = Queue() # FIFO Queue
    visited = [False for _ in range(n)]

    queue.put(start)

    while not queue.empty():
        curr_v = queue.get()
        visited[curr_v] = True # visit new vertex
        for neigh in range(n):
            if neigh != curr_v and abs(mat[curr_v][neigh]) > 0: # check the neighbours of current vertex
                if visited[neigh] == False:
                    queue.put(neigh)

    for i in range(n): # check if all vertecies were visited
        if visited[i] == False:
            return True
        
    return False



def is_reducible(mat):
    n = len(mat)

    for vertex in range(n): # check if every vertex can be visited from every possbile vertex
        flag = dfs(mat, vertex)
        if flag == True:
            return True

    return False

def is_reducible_2(mat):
    
    n = len(mat)

    for vertex in range(n): # check if every vertex can be visited from every possbile vertex
        flag = bfs(mat, vertex)
        if flag == True:
            return True
        
    return False


In [10]:
# size = int(input("Enter matrix size: "))
# mat = [0 for _ in range(size)]

example_irreducibe = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, -3, 3]
])

example_reducilbe = np.array([
    [1, 0, 0],
    [2, 3, 4],
    [5, 6, 7]
])

# for i in range(size):
#     row = np.array(input("").split())
#     mat[i] = row.astype(np.float64)

mat = np.random.randint(low = 2, high = 5, size=(3, 3))

print(f'current matrix: {mat}')
print(is_reducible(mat))

print(f'current matrix: {mat}')
print(is_reducible_2(mat))

print(f'current matrix: {example_irreducibe}')
print(is_reducible(example_irreducibe))


print(f'current matrix: {example_reducilbe}')
print(is_reducible(example_reducilbe))

print(f'current matrix: {example_irreducibe}')
print(is_reducible_2(example_irreducibe))


print(f'current matrix: {example_reducilbe}')
print(is_reducible_2(example_reducilbe))


current matrix: [[2 2 3]
 [4 4 2]
 [3 4 4]]
False
current matrix: [[2 2 3]
 [4 4 2]
 [3 4 4]]
False
current matrix: [[ 1  1  1]
 [ 2  2  2]
 [ 3 -3  3]]
False
current matrix: [[1 0 0]
 [2 3 4]
 [5 6 7]]
True
current matrix: [[ 1  1  1]
 [ 2  2  2]
 [ 3 -3  3]]
False
current matrix: [[1 0 0]
 [2 3 4]
 [5 6 7]]
True
